sudo: required
services:
  - docker

before_install: 
  - docker build -t  pehlivanalparslan/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true  pehlivanalparslan/docker-react npm run test

